# Generated by Django 5.0.4 on 2024-05-05 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('playerid', models.IntegerField(primary_key=True, serialize=False, verbose_name='球员ID')),
                ('icon_filename', models.CharField(default='default_icon.png', max_length=160, verbose_name='头像')),
                ('name', models.CharField(max_length=50, verbose_name='球员名')),
                ('chinaname', models.CharField(default='none', max_length=40, verbose_name='球员中文名')),
                ('position', models.CharField(default='none', max_length=20, verbose_name='位置')),
                ('nation', models.CharField(default='none', max_length=40, verbose_name='国籍')),
                ('height', models.IntegerField(default=0, verbose_name='身高')),
                ('weight', models.IntegerField(default=0, verbose_name='体重')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('prize', models.CharField(default='none', max_length=20, verbose_name='身价')),
            ],
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('teamid', models.IntegerField(primary_key=True, serialize=False, verbose_name='排名')),
                ('icon_filename', models.CharField(default='default_icon.png', max_length=150, verbose_name='图标')),
                ('name', models.CharField(max_length=40, verbose_name='球队名')),
                ('sum', models.IntegerField(default=0, verbose_name='场次')),
                ('goals', models.IntegerField(default=0, verbose_name='进球数')),
                ('miss', models.IntegerField(default=0, verbose_name='失球数')),
                ('clear', models.IntegerField(default=0, verbose_name='净胜球')),
                ('points', models.IntegerField(default=0, verbose_name='积分')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamid', models.IntegerField(primary_key=True, serialize=False, verbose_name='球队ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='球队英文名称')),
                ('shortname', models.CharField(max_length=20, unique=True, verbose_name='球队缩写')),
                ('chinaname', models.CharField(max_length=20, verbose_name='球队中文名称')),
                ('othername', models.CharField(max_length=50, verbose_name='球队中文别名')),
                ('foundtime', models.CharField(max_length=20, verbose_name='成立时间')),
                ('city', models.CharField(max_length=20, verbose_name='城市')),
                ('home', models.CharField(max_length=30, verbose_name='主场')),
                ('coach', models.CharField(max_length=30, verbose_name='教练')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('player_id', models.OneToOneField(db_column='playerid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='world.player', verbose_name='球员ID')),
                ('name', models.CharField(default='None', max_length=40, verbose_name='球员名')),
                ('chinaname', models.CharField(default='None', max_length=30, verbose_name='中文名')),
                ('sum', models.IntegerField(default=0, verbose_name='上场场次')),
                ('first', models.IntegerField(default=0, verbose_name='首发')),
                ('matchtime', models.IntegerField(default=0, verbose_name='出场时间')),
                ('goal', models.IntegerField(default=0, verbose_name='进球')),
                ('penalty', models.IntegerField(default=0, verbose_name='点球')),
                ('shooting', models.IntegerField(default=0, verbose_name='射门')),
                ('target', models.IntegerField(default=0, verbose_name='射正')),
                ('passing', models.IntegerField(default=0, verbose_name='过人')),
                ('free', models.IntegerField(default=0, verbose_name='任意球')),
                ('free_goal', models.IntegerField(default=0, verbose_name='任意球得分')),
                ('hitdoor', models.IntegerField(default=0, verbose_name='击中门框')),
                ('quick', models.IntegerField(default=0, verbose_name='快攻')),
                ('quick_atk', models.IntegerField(default=0, verbose_name='快攻进攻')),
                ('quick_goal', models.IntegerField(default=0, verbose_name='快攻进球')),
                ('lost_right', models.IntegerField(default=0, verbose_name='丢失球权')),
                ('passball', models.IntegerField(default=0, verbose_name='传球')),
                ('valid_passball', models.IntegerField(default=0, verbose_name='传球成功')),
                ('key_passball', models.IntegerField(default=0, verbose_name='关键传球')),
                ('midpass', models.IntegerField(default=0, verbose_name='传中球')),
                ('valid_midpass', models.IntegerField(default=0, verbose_name='传中球成功')),
                ('longpass', models.IntegerField(default=0, verbose_name='长传')),
                ('valid_longpass', models.IntegerField(default=0, verbose_name='长传成功')),
                ('lost_pass', models.IntegerField(default=0, verbose_name='传球被断')),
                ('breaking', models.IntegerField(default=0, verbose_name='解围')),
                ('valid_prevent', models.IntegerField(default=0, verbose_name='有效阻挡')),
                ('intercept', models.IntegerField(default=0, verbose_name='拦截')),
                ('preemption', models.IntegerField(default=0, verbose_name='抢断')),
                ('onebyone', models.IntegerField(default=0, verbose_name='1对1拼抢')),
                ('valid_onebyone', models.IntegerField(default=0, verbose_name='1对1拼抢成功')),
                ('handball', models.IntegerField(default=0, verbose_name='拳击球')),
                ('keeper_atk', models.IntegerField(default=0, verbose_name='守门员出击')),
                ('valid_atk', models.IntegerField(default=0, verbose_name='守门员出击成功')),
                ('high_atk', models.IntegerField(default=0, verbose_name='高空出击')),
                ('redcard', models.IntegerField(default=0, verbose_name='红牌')),
                ('yellowcard', models.IntegerField(default=0, verbose_name='黄牌')),
                ('foul', models.IntegerField(default=0, verbose_name='犯规')),
                ('violated', models.IntegerField(default=0, verbose_name='被侵犯')),
                ('offside', models.IntegerField(default=0, verbose_name='越位')),
                ('turnred', models.IntegerField(default=0, verbose_name='两黄变红')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='teamname',
            field=models.ForeignKey(db_column='teamname', default='None', on_delete=django.db.models.deletion.CASCADE, to='world.team', to_field='name', verbose_name='球队'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('matchid', models.IntegerField(primary_key=True, serialize=False, verbose_name='赛程ID')),
                ('hostgoal', models.IntegerField(verbose_name='主队分数')),
                ('guestgoal', models.IntegerField(verbose_name='客队分数')),
                ('date', models.CharField(max_length=20, verbose_name='比赛日期')),
                ('status', models.CharField(max_length=10, verbose_name='比赛状态')),
                ('guestteamid', models.ForeignKey(db_column='guestteamid', on_delete=django.db.models.deletion.CASCADE, related_name='guest_match', to='world.team', to_field='shortname', verbose_name='客队')),
                ('hostteamid', models.ForeignKey(db_column='hostteamid', on_delete=django.db.models.deletion.CASCADE, related_name='host_match', to='world.team', to_field='shortname', verbose_name='主队')),
            ],
        ),
    ]
