# Generated by Django 5.0.4 on 2024-05-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='matchsum',
            field=models.IntegerField(default=0, verbose_name='比赛场次'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='valid_passing',
            field=models.IntegerField(default=0, verbose_name='过人成功'),
        ),
    ]
