# Generated by Django 5.0.4 on 2024-05-05 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='id',
        ),
        migrations.AlterField(
            model_name='details',
            name='matchid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='world.match'),
        ),
    ]
