# Generated by Django 5.0.4 on 2024-05-05 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0006_remove_details_id_alter_details_matchid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='matchid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='world.match'),
        ),
    ]
