# Generated by Django 5.0.4 on 2024-05-05 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0008_alter_details_matchid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='guestats',
            new_name='guestatk',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='guestdanstk',
            new_name='guestdanatk',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='hostdanstk',
            new_name='hostdanatk',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='hostyelloe',
            new_name='hostyellow',
        ),
    ]
