# Generated by Django 5.0.4 on 2024-05-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0009_rename_guestats_details_guestatk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('shoot', models.IntegerField(default=0)),
                ('passball', models.IntegerField(default=0)),
                ('physics', models.IntegerField(default=0)),
                ('dribble', models.IntegerField(default=0)),
                ('defensive', models.IntegerField(default=0)),
                ('discipline', models.IntegerField(default=0)),
            ],
        ),
    ]
