# Generated by Django 5.0.4 on 2024-05-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0010_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='guestcontrol',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='details',
            name='hostcontrol',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
