# Generated by Django 5.0.4 on 2024-05-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0011_alter_details_guestcontrol_alter_details_hostcontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='icon_filename',
            field=models.CharField(default='default_icon.png', max_length=200, verbose_name='头像'),
        ),
    ]
